console.log("Promises File 1");

// Generic Example of a promise 

function calculateSquare(number){

   const promise = new Promise(function(resolve, reject){
      // Async action was generated by setTimeout Function.
      setTimeout(function() {
         if(typeof number !== 'number'){
            return reject(new Error('Arg of type number is expected'));
         }
         const result = number * number;
         resolve(result);
      }, 1000 );
   });

   return promise;
}

calculateSquare(2)  // Sincce it is a resolve the controle is going to 1st Function
.then( value => {
    console.log("Success : ", value);
}, value => {
    console.log("Error   : ", value);
}
);

calculateSquare('String') // Sincce it is a resolve the controle is going to 1st Function
.then( value => {
    console.log("Success : ", value);
}, value => {
    console.log("Error   : ", value);
}
);

console.log("End of Promise");